# Generated by Django 5.2 on 2025-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_type', models.CharField(choices=[('Moisture', 'Moisture'), ('Ash', 'Ash'), ('Fat', 'Fat'), ('Fiber', 'Fiber'), ('Protein', 'Protein'), ('Nitrogen', 'Nitrogen')], max_length=50)),
                ('result', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
